In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
data_root = "../../data"

In [3]:
device = "cpu"

## Define the Class

In [6]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [7]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [15]:
labels_map = {
    0: "T-Shirt",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle Boot",
}

In [21]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
y_pred_label = labels_map[y_pred.item()]
print(f"Predicted class: {y_pred_label}")

Predicted class: T-Shirt


In [12]:
print(logits)
print(pred_probab)

tensor([[ 0.0311,  0.0141,  0.0507, -0.0160,  0.0547,  0.0741, -0.0401, -0.0026,
         -0.0210, -0.1209]], grad_fn=<AddmmBackward0>)
tensor([[0.1028, 0.1010, 0.1048, 0.0980, 0.1052, 0.1073, 0.0957, 0.0994, 0.0975,
         0.0883]], grad_fn=<SoftmaxBackward0>)


## Model Layers

In [35]:
input_image = torch.rand(3,28,28)
print(input_image.size())
print(input_image)

torch.Size([3, 28, 28])
tensor([[[0.4600, 0.2317, 0.7261,  ..., 0.0493, 0.6569, 0.6611],
         [0.3970, 0.3299, 0.9435,  ..., 0.4273, 0.8525, 0.5626],
         [0.7843, 0.0381, 0.0377,  ..., 0.4530, 0.9247, 0.1575],
         ...,
         [0.2606, 0.1009, 0.6273,  ..., 0.1833, 0.3453, 0.2190],
         [0.3227, 0.9386, 0.1767,  ..., 0.4833, 0.6276, 0.4597],
         [0.4946, 0.1756, 0.2440,  ..., 0.1541, 0.1839, 0.4808]],

        [[0.6853, 0.0049, 0.6588,  ..., 0.8616, 0.4173, 0.4581],
         [0.9488, 0.6322, 0.7310,  ..., 0.6483, 0.8315, 0.7397],
         [0.3021, 0.5687, 0.3163,  ..., 0.2801, 0.9882, 0.2812],
         ...,
         [0.2952, 0.3513, 0.1320,  ..., 0.8198, 0.0857, 0.0592],
         [0.1378, 0.8945, 0.4855,  ..., 0.5929, 0.1325, 0.8611],
         [0.0094, 0.3097, 0.2163,  ..., 0.7618, 0.0650, 0.5235]],

        [[0.7108, 0.4525, 0.3804,  ..., 0.2040, 0.6629, 0.9217],
         [0.2438, 0.6897, 0.1415,  ..., 0.7507, 0.2965, 0.1404],
         [0.1649, 0.0246, 0.0183, 

In [50]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())
print(flat_image)

torch.Size([3, 784])
tensor([[0.4600, 0.2317, 0.7261,  ..., 0.1541, 0.1839, 0.4808],
        [0.6853, 0.0049, 0.6588,  ..., 0.7618, 0.0650, 0.5235],
        [0.7108, 0.4525, 0.3804,  ..., 0.3645, 0.9001, 0.8677]])


In [52]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())
print(hidden1)

torch.Size([3, 20])
tensor([[ 0.2313, -0.0910,  0.3339,  0.2543,  0.2411,  0.3131, -0.2133,  0.6825,
          0.3195, -0.6944, -0.1019, -0.3617, -0.1298,  0.1926,  0.2636,  0.1302,
         -0.1717, -0.0225, -0.5232, -0.5425],
        [-0.1347, -0.3392,  0.6145,  0.0062, -0.0454,  0.1923, -0.4902,  0.1536,
          0.3605, -0.1827,  0.2772, -0.5179, -0.1105, -0.1410,  0.1143,  0.3775,
         -0.0829, -0.1696, -0.5964, -0.0984],
        [-0.0017,  0.3053,  0.5913, -0.0441,  0.1507, -0.0249, -0.3393,  0.3150,
          0.0908, -0.5112,  0.0017, -0.3319, -0.1703, -0.2202,  0.4976,  0.1913,
         -0.2974,  0.1283, -0.3479, -0.2407]], grad_fn=<AddmmBackward0>)


In [53]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 0.2313, -0.0910,  0.3339,  0.2543,  0.2411,  0.3131, -0.2133,  0.6825,
          0.3195, -0.6944, -0.1019, -0.3617, -0.1298,  0.1926,  0.2636,  0.1302,
         -0.1717, -0.0225, -0.5232, -0.5425],
        [-0.1347, -0.3392,  0.6145,  0.0062, -0.0454,  0.1923, -0.4902,  0.1536,
          0.3605, -0.1827,  0.2772, -0.5179, -0.1105, -0.1410,  0.1143,  0.3775,
         -0.0829, -0.1696, -0.5964, -0.0984],
        [-0.0017,  0.3053,  0.5913, -0.0441,  0.1507, -0.0249, -0.3393,  0.3150,
          0.0908, -0.5112,  0.0017, -0.3319, -0.1703, -0.2202,  0.4976,  0.1913,
         -0.2974,  0.1283, -0.3479, -0.2407]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.2313, 0.0000, 0.3339, 0.2543, 0.2411, 0.3131, 0.0000, 0.6825, 0.3195,
         0.0000, 0.0000, 0.0000, 0.0000, 0.1926, 0.2636, 0.1302, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.0000, 0.6145, 0.0062, 0.0000, 0.1923, 0.0000, 0.1536, 0.3605,
         0.0000, 0.2772, 0.0000, 0.0000, 0.0000, 0.11

In [54]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

In [55]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

## Model Parameters

In [56]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0253, -0.0057,  0.0170,  ..., -0.0102, -0.0348,  0.0282],
        [-0.0147, -0.0179,  0.0176,  ...,  0.0158,  0.0203,  0.0103]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0034,  0.0246], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[-0.0265,  0.0436,  0.0136,  ..., -0.0088, -0.0277,  0.0361],
        [ 0.0392, -0.0391, -0.0325,  ...,  0.0213, -0.0169,  0.0335]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.bias | 